DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS eventGroup;
DROP TABLE IF EXISTS memberOf;
DROP TABLE IF EXISTS calendarEvent;
DROP TABLE IF EXISTS participants;
DROP TABLE IF EXISTS booked;